name: mediminder
description: "MediMinder – Gyógyszer és Orvosi Találkozó Kezelő"
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.0
  provider: ^6.1.0
  google_sign_in: ^6.2.0
  flutter_local_notifications: ^18.0.0
  flutter_secure_storage: ^9.2.0
  intl: ^0.20.0
  google_fonts: ^6.2.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
